version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: produtos_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  rest:
    build:
      context: ./Servidor
      dockerfile: REST/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  soap:
    build:
      context: ./Servidor
      dockerfile: SOAP/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      
  graphql:
    build:
      context: ./Servidor
      dockerfile: GraphQL/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      
  grpc:
    build:
      context: ./Servidor
      dockerfile: GRPC/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  websocket:
    build:
      context: ./Servidor
      dockerfile: WebSockets/Dockerfile
    ports:
      - "6789:6789"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongodb_data:
  rabbitmq_data:
