services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: produtos_db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  rest:
    build:
      context: ./Servidor
      dockerfile: REST/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_HOST=rabbitmq

  soap:
    build:
      context: ./Servidor
      dockerfile: SOAP/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_HOST=rabbitmq
      
  graphql:
    build:
      context: ./Servidor
      dockerfile: GraphQL/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_HOST=rabbitmq
      
  grpc:
    build:
      context: ./Servidor
      dockerfile: GRPC/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_HOST=rabbitmq

  websocket:
    build:
      context: ./Servidor
      dockerfile: WebSockets/Dockerfile
    ports:
      - "6789:6789"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  websocket_server:
    build:
      context: ./Servidor
      dockerfile: websocket_server.Dockerfile
    ports:
      - "6789:6789"
    depends_on:
      - rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:
