version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: produtos_db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  rest:
    build:
      context: ./Servidor
      dockerfile: REST/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      - rabbitmq

  soap:
    build:
      context: ./Servidor
      dockerfile: SOAP/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      - rabbitmq
      
  graphql:
    build:
      context: ./Servidor
      dockerfile: GraphQL/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - mongodb
      - rabbitmq
      
  grpc:
    build:
      context: ./Servidor
      dockerfile: GRPC/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
      - rabbitmq

  websocket:
    build:
      context: ./Servidor
      dockerfile: WebSockets/Dockerfile
    ports:
      - "6789:6789"
    depends_on:
      - rest
      - soap
      - graphql
      - grpc
      - rabbitmq
    restart: unless-stopped

volumes:
  mongodb_data:
  rabbitmq_data:
