services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: produtos_db

  rest:
    build:
      context: ./Servidor
      dockerfile: REST/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      
  soap:
    build:
      context: ./Servidor
      dockerfile: SOAP/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      
  graphql:
    build:
      context: ./Servidor
      dockerfile: GraphQL/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - mongodb
      
  grpc:
    build:
      context: ./Servidor
      dockerfile: GRPC/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
